Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/EachWithObject:
  Enabled: false

# Style/HashEachMethods:
#   Enabled: true

# Style/HashTransformKeys:
#   Enabled: true

# Style/HashTransformValues:
#   Enabled: true

Style/EmptyMethod:
  Enabled: false

# Metrics/BlockLength:
#   Enabled: false

# Layout/LineLength:
#   Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Metrics/AbcSize:
#   Enabled: false